import '../styles/globals.css';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR">
      <Head>
        <title>فروشگاه آنلاین</title>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
